services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    working_dir: /tf
    environment:
      - AWS_ACCESS_KEY_ID=AKIA6GBMGTTOMNRGVKBJ
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=eu-north-1
      - TF_WORKSPACE=${TF_WORKSPACE}

